### PR TITLE
Fix behavior of `copy` and `similar`

### LINKED ISSUE #11: Bug: `copy` and `similar` should return parent array type, not ReadOnlyArray
@bkamins @markmbaum 

There was inadvertently introduced in #9. It hasn't yet been released though.

On 0.1, `ReadOnlyArray` has the following behavior:

```julia
julia> X = ReadOnlyArray([1, 2])
2-element ReadOnlyArray{Int64, 1, Vector{Int64}}:
 1
 2

julia> c = copy(X)
2-element Vector{Int64}:
 1
 2

julia> c .= c .^ 2
2-element Vector{Int64}:
 1
 4
```

Which makes ReadOnlyArrays compatible with many libraries that create buffers from the input array. You would store your input data in a `ReadOnlyArray`, and expect the underlying package to make copies of it and then operate on the copy.

`similar` works by creating a copy of the parent array, rather than another `ReadOnlyArray`.

However, after 0.1, this is broken:

```julia
julia> X = ReadOnlyArray([1, 2])
2-element ReadOnlyVector{Int64, Vector{Int64}}:
 1
 2

julia> similar(X)
2-element ReadOnlyVector{Int64, Vector{Int64}}:
 0
 0
```

`similar` does not make sense as an operation unless you can mutate the elements, so I think this was introduced by mistake in #9.

For example, this means that core operations like `copy` will just break:

```julia
julia> c = copy(X)
ERROR: CanonicalIndexError: setindex! not defined for ReadOnlyVector{Int64, Vector{Int64}}
Stacktrace:
 [1] error_if_canonical_setindex(::IndexLinear, A::ReadOnlyVector{Int64, Vector{Int64}}, ::Int64)
   @ Base ./abstractarray.jl:1404
 [2] setindex!
   @ ./abstractarray.jl:1395 [inlined]
 [3] copyto_unaliased!
   @ ./abstractarray.jl:1088 [inlined]
 [4] copyto!(dest::ReadOnlyVector{Int64, Vector{Int64}}, src::ReadOnlyVector{Int64, Vector{Int64}})
   @ Base ./abstractarray.jl:1068
 [5] copymutable(a::ReadOnlyVector{Int64, Vector{Int64}})
   @ Base ./abstractarray.jl:1202
 [6] copy(a::ReadOnlyVector{Int64, Vector{Int64}})
   @ Base ./abstractarray.jl:1145
 [7] top-level scope
   @ REPL[5]:1
```

I think this should be reversed to the behavior of 0.1.

### PR DESCRIPTION
**Pull request by MilesCranmer**
Fixes #11

### CODE REVIEW

**Review by bkamins — APPROVED** [review]

File: test/runtests.jl [hunk 1]
```diff
@@ -51,6 +51,12 @@ end
         fa = f()
         @test fa isa ReadOnlyArray{Float64,2}
         @test fa == x
+
+        a = ReadOnly([1, 2])
```
Comment (timholy) [inline test/runtests.jl:55]: `ReadOnly` doesn't seem to be defined:
```
(ReadOnlyArrays) pkg> test
  No Changes to `~/.julia/dev/ReadOnlyArrays/Project.toml`
  No Changes to `~/.julia/dev/ReadOnlyArrays/Manifest.toml`
     Testing ReadOnlyArrays
      Status `/tmp/jl_Dsjfkt/Project.toml`
  [988b38a3] ReadOnlyArrays v0.2.0 `~/.julia/dev/ReadOnlyArrays`
  [8dfed614] Test
      Status `/tmp/jl_Dsjfkt/Manifest.toml`
  [988b38a3] ReadOnlyArrays v0.2.0 `~/.julia/dev/ReadOnlyArrays`
  [2a0f44e3] Base64
  [b77e0a4c] InteractiveUtils
  [56ddb016] Logging
  [d6f4376e] Markdown
  [9a3f8284] Random
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization
  [8dfed614] Test
     Testing Running tests...
Test Summary: | Pass  Total  Time
Constructors  |    3      3  0.0s
misc: Error During Test at /home/tim/.julia/dev/ReadOnlyArrays/test/runtests.jl:46
  Got exception outside of a @test
  UndefVarError: `ReadOnly` not defined
  Stacktrace:
    [1] macro expansion
      @ ~/.julia/dev/ReadOnlyArrays/test/runtests.jl:55 [inlined]
    [2] macro expansion
      @ ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
    [3] macro expansion
      @ ~/.julia/dev/ReadOnlyArrays/test/runtests.jl:47 [inlined]
    [4] macro expansion
      @ ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
    [5] top-level scope
      @ ~/.julia/dev/ReadOnlyArrays/test/runtests.jl:14
    [6] include(fname::String)
      @ Base.MainInclude ./client.jl:489
    [7] top-level scope
      @ none:6
    [8] eval
      @ ./boot.jl:385 [inlined]
    [9] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:291
   [10] _start()
      @ Base ./client.jl:552
Test Summary: | Pass  Error  Total  Time
Interface     |   22      1     23  1.7s
  size        |    4             4  0.0s
  indexing    |    3             3  0.0s
  iteration   |   11            11  0.1s
  misc        |    4      1      5  1.6s
ERROR: LoadError: Some tests did not pass: 22 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/tim/.julia/dev/ReadOnlyArrays/test/runtests.jl:13
ERROR: Package ReadOnlyArrays errored during testing
```

Comment (timholy) [reply test/runtests.jl:55]: xref #14
